export const WINDOW_WIDTH = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth
export const WINDOW_HEIGHT = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight
export const WORLD_SIZE = { width: 1024, height: 900 }
export const ASSETS_URL = '../assets'
export const NBR_POPBOX_COLONNE = 2
export const POS_Y_POPBOX = 400;
export const NBR_POPBOX_LIGNE = 4;
export const DIST_LIGNE = 400;
export const DIST_COLONNE = 250;
export const LIMIT_TOP = 100;
export const LIMIT_BOTTOM = 1100;
export const LIMIT_LEFT = 100;
